https://www.youtube.com/watch?v=R6hcxMMOrPE

In [7]:
import torch
from transformers import BertTokenizer, BertForMaskedLM

In [8]:
# inizialize two models the tokenizer and model:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [9]:
#we take a text and split every sentence
with open('./clean.txt') as fp:
    text = fp.read().split('\n')
text[:5]

['From my grandfather Verus I learned good morals and the government of my temper.',
 'From the reputation and remembrance of my father, modesty and a manly character.',
 'From my mother, piety and beneficence, and abstinence, not only from evil deeds, but even from evil thoughts; and further, simplicity in my way of living, far removed from the habits of the rich.',
 'From my great-grandfather, not to have frequented public schools, and to have had good teachers at home, and to know that on such things a man should spend liberally.',
 "From my governor, to be neither of the green nor of the blue party at the games in the Circus, nor a partizan either of the Parmularius or the Scutarius at the gladiators' fights; from him too I learned endurance of labour, and to want little, and to work with my own hands, and not to meddle with other people's affairs, and not to be ready to listen to slander."]

In [13]:
#tokenizer
inputs = tokenizer(text, return_tensors='pt', max_length = 512, truncation = True, padding = 'max_length')
inputs

{'input_ids': tensor([[  101,  2013,  2026,  ...,     0,     0,     0],
        [  101,  2013,  1996,  ...,     0,     0,     0],
        [  101,  2013,  2026,  ...,     0,     0,     0],
        ...,
        [  101,  3459,  2185,  ...,     0,     0,     0],
        [  101,  2043, 15223,  ...,     0,     0,     0],
        [  101,  7887,  3288,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [15]:
#we need 2 thing to train bert: input_ids and labels
#before we mask our input_ids we need to create a copy to use it as our labels 

inputs['labels'] = inputs.input_ids.detach().clone()
input
#so now we have a copy of the labels in 'labels': tensor

{'input_ids': tensor([[  101,  2013,  2026,  ...,     0,     0,     0],
        [  101,  2013,  1996,  ...,     0,     0,     0],
        [  101,  2013,  2026,  ...,     0,     0,     0],
        ...,
        [  101,  3459,  2185,  ...,     0,     0,     0],
        [  101,  2043, 15223,  ...,     0,     0,     0],
        [  101,  7887,  3288,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([[  101,  2013,  2026,  ...,     0,     0,     0],
        [  101,  2013,  1996,  ...,     0,     0,     0],
        [  101,  2013, 

In [17]:
#now we have to create our mask
#each token that is not a special token has 15% to be our mask
rand = torch.rand(inputs.input_ids.shape)
rand.shape
#where 507 is the number of sequence that we have and 512 is the number of token each sequence has 

torch.Size([507, 512])

In [19]:
rand
#are floats between 0 and 1 

tensor([[0.5300, 0.1558, 0.4651,  ..., 0.7261, 0.3409, 0.7595],
        [0.8028, 0.1229, 0.2496,  ..., 0.7893, 0.1920, 0.3409],
        [0.0491, 0.2785, 0.1044,  ..., 0.9155, 0.2993, 0.2099],
        ...,
        [0.4329, 0.3505, 0.0076,  ..., 0.3935, 0.4190, 0.6622],
        [0.9331, 0.2728, 0.4564,  ..., 0.2006, 0.8533, 0.9336],
        [0.1408, 0.1513, 0.8164,  ..., 0.4342, 0.3410, 0.1942]])

In [21]:
#we want to mask everything that has the value under 0.15 and is not a padding token or classifier token or sequence token
mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102) * (inputs.input_ids != 0)
mask_arr
#now we have the mask array

tensor([[False, False, False,  ..., False, False, False],
        [False,  True, False,  ..., False, False, False],
        [False, False,  True,  ..., False, False, False],
        ...,
        [False, False,  True,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [24]:
#now we want to take the indicies of each value that has true label for each sequence
selection = []
for i in range(mask_arr.shape[0]):
    selection.append(torch.flatten(mask_arr[i].nonzero()).tolist()
)

selection[:5]

[[15],
 [1, 8, 12, 15],
 [2, 3, 4, 13, 14, 18, 31, 36, 37],
 [8, 11, 26, 35],
 [10, 16, 20, 28, 30, 33, 44, 45, 47, 55, 59, 61, 68, 70, 73, 83, 86, 90, 91]]

In [28]:
#now we want to set the values equal to 103 for each indices we have in each sequence 
for i in range(mask_arr.shape[0]):
    inputs.input_ids[i, selection[i]] = 103

inputs.input_ids

tensor([[  101,  2013,  2026,  ...,     0,     0,     0],
        [  101,   103,  1996,  ...,     0,     0,     0],
        [  101,  2013,   103,  ...,     0,     0,     0],
        ...,
        [  101,  3459,   103,  ...,     0,     0,     0],
        [  101,  2043, 15223,  ...,     0,     0,     0],
        [  101,  7887,  3288,  ...,     0,     0,     0]])

In [30]:
#we need to process them into a dateloader during training, but first we need to convert them into pytorch objects 
class MeditationsDataset(torch.utils.data.Dataset): #pass the class
    def __init__(self, encodings): #inizialization function
        self.encodings = encodings #assign encodins to attributes 
    #the dataloader expects 2 additional functions for methods
    #the get tems that you can get a dictionary formatted batch of those items
    def __getitem__(self, idx):
        return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
    #check the lenght of the dataset that it's looking at
    def __len__(self):
        return len(self.encodings.input_ids)

#so this is our class that handle the formatting our data in data objects

In [31]:
#create a new data variable 
dataset = MeditationsDataset(inputs)

In [32]:
#inizialize the dataloader
dataloader = torch.utils.data.DataLoader(dataset, batch_size = 16, shuffle = True)

In [34]:
#now we are ready to actually training 
#first we need to set the training paramters 

#we check if we have a gpu
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [36]:
model.to(device)

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [38]:
#we have to activate our model in training mode
model.train()

#we need to inizialize an optimizer - in this case AdamW
from transformers import AdamW
optim = AdamW(model.parameters(), lr=1e-5)

/Users/mae/opt/miniconda3/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [40]:
#now we can training 
from tqdm import tqdm #allows to create a progress bar during training otherwise we just sat down we don't see any updates

epochs = 2 #we don't want to trian that much

for epochs in range(epochs):
    loop = tqdm(dataloader, leave = True) #set the tain loop
    for batch in loop: 
        optim.zero_grad() #first we want to calculate our gradient
        input_ids = batch ['input_ids'].to(device)
        attention_mask = batch ['attention_mask'].to(device)
        labels = batch ['labels'].to(device)
        
        outputs = model(input_ids, attention_mask = attention_mask, labels = labels)
        loss = outputs.loss
        loss.backward() #calculate the loss for every parameter in our model
        optim.step() #we want to optimize every parameter based on our loss 
        
        loop.set_description(f'Epoch {epochs}')
        loop.set_postfix(loss = loss.item())

  0%|          | 0/32 [00:00<?, ?it/s]/var/folders/8s/5jql9hyd6p7cp25xdxcgjp4c0000gn/T/ipykernel_4595/3682194249.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
Epoch 0:  41%|████      | 13/32 [04:15<06:14, 19.69s/it, loss=9.04]


KeyboardInterrupt: 